config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  post "sign_in", to: "authentications#sign_in", as: :sign_in
  delete "sign_out", to: "authentications#sign_out", as: :sign_out

  resources :products
  resources :users
  resources :exports, only: [:index, :create] do
    member do
      post :download
    end
  end
end

app/views/shared/_dashboard_header.html.erb

<!-- Desktop Header -->
<header class="w-full items-center bg-white py-2 px-6 hidden sm:flex">
    <div class="w-1/2"></div>
    <div x-data="{ isOpen: false }" class="relative w-1/2 flex justify-end">
        <button @click="isOpen = !isOpen" class="realtive z-10 w-12 h-12 rounded-full overflow-hidden border-4 border-gray-400 hover:border-gray-300 focus:border-gray-300 focus:outline-none">
            <img src="https://source.unsplash.com/uJ8LNVCBjFQ/400x400">
        </button>
        <button x-show="isOpen" @click="isOpen = false" class="h-full w-full fixed inset-0 cursor-default"></button>
        <div x-show="isOpen" class="absolute w-32 bg-white rounded-lg shadow-lg py-2 mt-16">
            <%= link_to "Sign Out", sign_out_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "block px-4 py-2 account-link hover:text-white"  %>
        </div>
    </div>
</header>

<!-- Mobile Header & Nav -->
<header x-data="{ isOpen: false }" class="w-full bg-sidebar py-5 px-6 sm:hidden">
    <div class="flex items-center justify-between">
        <a href="index.html" class="text-white text-3xl font-semibold uppercase hover:text-gray-300">Admin</a>
        <button @click="isOpen = !isOpen" class="text-white text-3xl focus:outline-none">
            <i x-show="!isOpen" class="fas fa-bars"></i>
            <i x-show="isOpen" class="fas fa-times"></i>
        </button>
    </div>

    <!-- Dropdown Nav -->
    <nav :class="isOpen ? 'flex': 'hidden'" class="flex flex-col pt-4">
       
        <a href="index.html" class="flex items-center active-nav-link text-white py-2 pl-4 nav-item">
            <i class="fas fa-tags mr-3"></i>
            Products
        </a>
        <a href="index.html" class="flex items-center active-nav-link text-white py-2 pl-4 nav-item">
            <i class="fas fa-user mr-3"></i>
            Users
        </a>
       
        <%= link_to sign_out_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item" do %>
            <i class="fas fa-sign-out-alt mr-3"></i>
            Sign Out
        <% end %>
    </nav>
    <button class="w-full bg-white cta-btn font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center">
        <i class="fas fa-plus mr-3"></i> New Product
    </button>
</header>

app/views/shared/_dashboard_sidebar.html.erb
<aside class="relative bg-sidebar h-screen w-64 hidden sm:block shadow-xl">
    <div class="p-6">
        <%= link_to "Admin", products_path, class: "text-white text-3xl font-semibold uppercase hover:text-gray-300" %>
        <%= button_to '<i class="fas fa-plus mr-3"></i> New Product'.html_safe, new_product_path, 
            method: :get, 
            form_class: "w-full bg-white cta-btn font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center" %>
    </div>


    <nav class="text-white text-base font-semibold pt-3">
        <%= link_to products_path, class: "flex items-center #{ controller.controller_name == 'products' ? 'active-nav-link' : '' } text-white py-4 pl-6 nav-item" do %>
            <i class="fas fa-tags mr-3"></i>
            Products
        <% end %>
       
        <%= link_to exports_path, class: "#{controller.controller_name == 'exports' ? 'active-nav-link' : '' } flex items-center text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item" do %>
            <i class="fas fa-file mr-3"></i>
            Exports
        <% end %>
    </nav>
</aside>

app/views/shared/_flash_messages.html.erb
<!-- app/views/shared/_flash_messages.html.erb -->
<% if flash.any? %>
  <div data-controller='flash-message' class='inset-0 p-6 items-start justify-end'>
    <div class='flex flex-col items-center justify-center'>
      <% flash.each do |type, message| %>
        <div class='relative flex px-4 py-3 space-x-2 border <%= color_classes(type) %>' role='alert'>
            <strong class='font-bold'><%= message %></strong>
            <span class='pl-5'>
            <%= heroicon 'x-mark', options: { class: 'w-6 h-6 fill-current', role: 'button' } %>
        </span>
    </div>
      <% end %>
    </div>
  </div>
<% end %>