config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  post "sign_in", to: "authentications#sign_in", as: :sign_in
  delete "sign_out", to: "authentications#sign_out", as: :sign_out

  resources :products
  resources :users
  resources :exports, only: [:index, :create] do
    member do
      post :download
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in?
  def index
  end
end

app/views/home/_login_form.html.erb
<%= form_for :auth, url: sign_in_url, method: :post, class: "space-y-6"  do |f| %>
    <div>
        <%= f.label :email, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
            <%= f.email_field :email, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", required: true, id: "email", autocomplete: "email" %>
        </div>
    </div>
    <div>
        <div class="flex items-center justify-between">
            <%= f.label :password, class: "block text-sm font-medium leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
            <%= f.password_field :password, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", required: true, id: "password", autocomplete: "current-password" %>
        </div>
    </div>
    <div>
        <%= f.button :submit, class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
            Submit
        <% end %>
        
    </div>
    <div>
<% end %>

app/views/home/index.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <%= image_tag("logo.png", class: "mx-auto h-10 w-auto", alt: "Kawan Lama Group") %>
    
    <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Sign in to your account</h2>
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= render "login_form" %>
  </div>
</div>