config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  post "sign_in", to: "authentications#sign_in", as: :sign_in
  delete "sign_out", to: "authentications#sign_out", as: :sign_out

  resources :products
  resources :users
  resources :exports, only: [:index, :create] do
    member do
      post :download
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_product, against: [:name, :sku, :description]


  validates_presence_of :name, :sku, :count, :description
  validates_uniqueness_of :sku
  validates_numericality_of :count

  mount_uploader :first_photo, ProductUploader
  mount_uploader :second_photo, ProductUploader
  mount_uploader :third_photo, ProductUploader

  scope :order_by_created, -> (q) { order(created_at: q) }
  scope :ordered_by, -> (key, value) { order("#{key} #{value}") }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "dashboard"

  before_action :is_logged_in?
  before_action :is_admin?, except: [:index, :show]
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    page = !params[:page].present? ? 1 : params[:page]
    @products = if params[:search].present?
      ProductSearch.new.search(
        params[:search][:q],
        params[:search][:order],
        params[:search][:sort]
      ).page(page).per(10).without_count
    else
      Product.order_by_created(:desc).page(page).per(10).without_count
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save!
      flash[:success] = "Product has been created"
      redirect_to products_url, format: :html
    else
      flash[:error] = @product.errors.full_messages
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product has been updated"
      redirect_to product_url(@product), format: :html
    else
      flash[:error] = @product.errors.full_messages
      render :new
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = "Product has been deleted"
    else
      flash[:error] = "Failed to delete product"
    end
    redirect_to product_url, format: :html
  end

  private
    def product_params
      params.require(:product).permit(:name, :sku, :count, :description, :first_photo, :second_photo, :third_photo, :submit)
    end

    def find_product
      @product = Product.find(params[:id])
    end

end

app/views/products/_form.html.erb
<%= form_for @product, class: "space-y-6"  do |f| %>
    <div>
        <%= f.label :name, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
            <%= f.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", required: true, id: "product_name" %>
        </div>
    </div>
    <div>
        <div class="flex items-center justify-between">
            <%= f.label :sku, class: "block text-sm font-medium leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
            <%= f.text_field :sku, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", required: true, id: "product_sku" %>
        </div>
    </div>
    <div>
        <div class="flex items-center justify-between">
            <%= f.label :description, class: "block text-sm font-medium leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
            <%= f.text_area :description, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", required: true, id: "product_sku" %>
        </div>
    </div>
    <div>
        <div class="flex items-center justify-between">
            <%= f.label :count, class: "block text-sm font-medium leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
            <%= f.number_field :count, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", required: true, id: "product_count" %>
        </div>
    </div>
    <div>
        <div class="flex items-center justify-between">
            <%= f.label :first_photo, class: "block text-sm font-medium leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
            <%= f.file_field :first_photo, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", id: "product_count" %>
            <%- if @product.first_photo.present? %>
                <%= image_tag(@product.first_photo_url(:thumb)) %>
            <% end %>
        </div>
    </div>
    <div>
        <div class="flex items-center justify-between">
            <%= f.label :second_photo, class: "block text-sm font-medium leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
            <%= f.file_field :second_photo, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", id: "product_count" %>
            <%- if @product.second_photo.present? %>
                <%= image_tag(@product.second_photo_url(:thumb)) %>
            <% end %>
        </div>
    </div>
    <div>
        <div class="flex items-center justify-between">
            <%= f.label :third_photo, class: "block text-sm font-medium leading-6 text-gray-900" %>
        </div>
        <div class="mt-2">
            <%= f.file_field :third_photo, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", id: "product_count" %>
            <%- if @product.third_photo.present? %>
                <%= image_tag(@product.third_photo_url(:thumb)) %>
            <% end %>
        </div>
    </div>
    <div class="mt-2">
        <%= f.submit "Save", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
            Submit
        <% end %>
    </div>
    <div>
<% end %>

app/views/products/_product_list.html.erb
<%- products.each do |p| %>
    <tr>
        <td class="text-center py-3 px-4 justify-center">
            <span class="flex items-center justify-center m-2">
                <%= image_tag p.first_photo_url(:thumb) rescue "" %>
            </span>
        </td>
        <td class="w-1/3 text-left py-3 px-4">
            <%= link_to p.sku, product_path(p) %>
        </td>
        <td class="w-1/3 text-left py-3 px-4">
            <%= p.name %>
        </td>
        <td class="text-left py-3 px-4">
            <%= p.count %>
        </td>
        <%- if current_user.is_admin? %>
            <td class="text-left py-3 px-4">
                <%= button_to "Edit", edit_product_path(p), method: :get, 
                    form_class: "w-full bg-white cta-btn font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center" 
                %>
                <%= button_to "Delete", product_path(p), method: :delete, 
                    form_class: "w-full bg-red-700 text-slate-200 font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}
                %>
            </td>
        <% end %>
        
    </tr>
<% end %>

app/views/products/_search_form.html.erb
<%= form_for :search, url: products_path, method: :get do |f| %>
    <%= f.search_field :q, value: (params[:search][:q] rescue nil), placeholder: "Search" %>
    <%= f.select :order, 
        options_for_select(order_params, (params[:search][:order] rescue nil)), 
        {prompt: "Order By"}, 
        {class: "w-36 px-2 py-2 mb-2"} %>
    <%= f.select :sort, 
        options_for_select(sorting_params, (params[:search][:sort] rescue nil)),
        {prompt: "Sort"}, 
        {class: "w-32 px-2 py-2 mb-2"} %>
    <%= f.submit :search, class: "w-36 px-2 py-2 mb-2 bg-indigo-600 text-white" %>
<% end %>

app/views/products/index.html.erb
 <div class="w-full overflow-x-hidden border-t flex flex-col">
    <main class="w-full flex-grow p-6">
        <h1 class="text-3xl text-black pb-6">Dashboard</h1>
            <div class="w-full mt-12">
                <div>
                    <p class="text-xl pb-3 flex items-center">
                        <i class="fas fa-list mr-3"></i> Products
                    </p>
                    <%= render "search_form"  %>
                </div>
                <div class="bg-white overflow-auto">
                    <table class="min-w-full bg-white">
                        <thead class="bg-gray-800 text-white">
                            <tr>
                                <th class="justify-center">Photo</th>
                                <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">SKU</th>
                                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Name</th>
                                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Count</th>
                                <%- if current_user.is_admin? %>
                                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Actions</th>
                                <% end %>
                            </tr>
                        </thead>
                        <tbody class="text-gray-700">
                            <%= render "product_list", products: @products %>
                        </tbody>
                    </table>
                </div>
            </div>
        <div class="mt-10">
            <%= link_to_prev_page @products, t('views.pagination.prev').html_safe, class: "bg-white hover:bg-gray-100 text-gray-800 font-light py-2 px-4 border border-gray-400 rounded shadow mx-1" %>
            <%= link_to_next_page @products, t('views.pagination.next').html_safe, class: "bg-white hover:bg-gray-100 text-gray-800 font-light py-2 px-4 border border-gray-400 rounded shadow mx-1" %>
        <div>
    </main>
    
    <footer class="w-full bg-white text-right p-4">
    <div class="mt-2">
        <%= button_to '<i class="fas fa-plus mr-3"></i> Export'.html_safe, exports_path, 
            method: :post, 
            form_class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" 
        %>
    </div>
    </footer>
</div>

app/views/products/new.html.erb
<div class="w-full overflow-x-hidden border-t flex flex-col">
    <main class="w-full flex-grow p-6">
        <h1 class="text-3xl text-black pb-6">Create Product</h1>
            <div class="w-full mt-12">
                <div class="bg-white overflow-auto">
                    <div class="mt-15 sm:mx-auto sm:w-full sm:max-w-sm">
                        <%= render "form" %>
                    </div>
                </div>
            </div>
        <div class="">
        <div>
    </main>
    
    <footer class="w-full bg-white text-right p-4">
    </footer>
</div>

app/views/products/show.html.erb
<div class="w-full overflow-x-hidden border-t flex flex-col">
    <main class="w-full flex-grow p-6">
        <h1 class="text-3xl text-black pb-6"><%= @product.name %></h1>
            <div class="w-full mt-12">
                <p class="text-xl pb-3 flex items-center">
                    <i class="fas fa-tag mr-3"></i> <%= @product.sku %>
                </p>
                <div class="bg-white overflow-auto">
                    
                    <div class="container mx-auto px-2 mt-2 mb-2">
                        <strong>Description</strong>
                        <p><%= @product.description %></p>
                    </div>
                    <div class="gap-8 columns-3 px-4 mt-20">
                        <%= image_tag @product.first_photo_url, class: "w-full aspect-square" if @product.first_photo.present? %>
                    </div>
                    <div class="gap-8 columns-3 px-4 mt-20">
                        <%= image_tag @product.second_photo_url, class: "w-full aspect-square" if @product.second_photo.present? %>
                    </div>
                    <div class="gap-8 columns-3 px-4 mt-20">
                        <%= image_tag @product.third_photo_url, class: "w-full aspect-square" if @product.third_photo.present? %>
                    </div>
                </div>
            </div>
    </main>
    
    <footer class="w-full bg-white text-right p-4">
    </footer>
</div>



