config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  post "sign_in", to: "authentications#sign_in", as: :sign_in
  delete "sign_out", to: "authentications#sign_out", as: :sign_out

  resources :products
  resources :users
  resources :exports, only: [:index, :create] do
    member do
      post :download
    end
  end
end

app/models/export.rb
require 'csv'
class Export < ApplicationRecord
  belongs_to :user

  STATUS = ["InProgress", "Finished"]

  default_scope -> { includes(:user) }

  ## Somehow Doens't work on RSpec
  before_validation :set_initial_status, on: :create

  validates_presence_of :status, :user_id
  validates_inclusion_of :status, in: STATUS

  ## Somehow it doesn't work
  # delegate :name, to: :user
  # delegate :email, to: :user

  # mount_uploader :file, ExportUploader
  after_create :create_file


  ## Somehow doesn't work on RSpec
  def set_initial_status
    self.status = "InProgress"
  end

  def file_name
    "export_#{id}.csv"
  end

  def file_path
    Rails.root.join("public/exports/#{file_name}")
  end

  def finished?
    status == "Finished"
  end

  ## Hacking delegate
  [:name, :email].each do |item|
    define_method "user_#{item}" do
      user.send(item)
    end
  end

  def create_file
    CSV.open(file_path, "w") do |csv|
      csv << ["SKU", "Name", "Count"]
    end
    ExportJob.perform_later(self)
  end

  def export_data
    CSV.open(file_path, "a") do |csv|
      Product.find_each(batch_size: 1000).each do |p|
        csv << [p.sku, p.name, p.count]
      end
    end
    self.update(status: "Finished")
  end
end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  before_action :is_logged_in?
  before_action :set_export, only: [:download]

  layout "dashboard"

  def index
    page = !params[:page].present? ? 1 : params[:page]
    @exports = Export.where(user: current_user).page(page).per(10)
  end

  def create
    @export = current_user.exports.create
    if @export
      flash[:success] = "Export has been created"
      redirect_to exports_url, format: :html
    else
      flash[:error] = "Failed to export data"
      redirect_to products_url, format: :html
    end
  end

  def download
    if check_ownership?(@export.user)
      send_file @export.file_path, disposition: 'attachment', type: "text/csv", file_name: @export.file_name
    else
      flash[:error] = "You dont have permission on this"
      redirect_to exports_url, format: :html
    end
  end

  private
    def check_ownership?(export_owner)
      export_owner == current_user
    end

    def set_export
      @export = Export.find(params[:id])
    end
end

app/helpers/exports_helper.rb
module ExportsHelper
end

app/views/exports/_export_list.html.erb
<%- exports.each do |export| %>
    <tr>
        <td class="w-1/3 text-left py-3 px-4">
            <%= export.id %>
        </td>
        <td class="w-1/3 text-left py-3 px-4">
            <%= export.user_name %>
        </td>
        <td class="w-1/3 text-left py-3 px-4">
            <%= export.status %>
        </td>
        <td class="text-left py-3 px-4">
            <%- if export.finished? %>
                <%= button_to "Download", download_export_path(export), method: :post, 
                    form_class: "w-full bg-white cta-btn font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center", data: { turbo: false }
                %>
            <% end %>
        </td>        
    </tr>
<% end %>

app/views/exports/index.html.erb
 <div class="w-full overflow-x-hidden border-t flex flex-col">
    <main class="w-full flex-grow p-6">
        <h1 class="text-3xl text-black pb-6">Export</h1>
            <div class="w-full mt-12">
                <div class="bg-white overflow-auto">
                    <table class="min-w-full bg-white">
                        <thead class="bg-gray-800 text-white">
                            <tr>
                                <th class="justify-center">Export ID</th>
                                <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">User</th>
                                <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Status</th>
                                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="text-gray-700">
                            <%= render "export_list", exports: @exports %>
                        </tbody>
                    </table>
                </div>
            </div>
        <div class="">
            <%= paginate @exports %>
        <div>
    </main>
    
    <footer class="w-full bg-white text-right p-4">
    </footer>
</div>